{
 "title": "Alation Analytics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UPTIME",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Load (5 min)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Load (15 min)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Maintenance Sessions",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "n_users" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization (Percent) ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "cpu" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       { "params": [ " *-1 + 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Free Memory (Percent)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mem (Total, Used)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       { "params": [ "Total (GB)" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       { "params": [ "Used (GB)" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Postgres Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Rows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Fetched" ], "type": "alias" }
      ],
      [
       { "params": [ "tup_returned" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Returned" ], "type": "alias" }
      ],
      [
       { "params": [ "tup_inserted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Inserted" ], "type": "alias" }
      ],
      [
       { "params": [ "tup_updated" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Updated" ], "type": "alias" }
      ],
      [
       { "params": [ "tup_deleted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Deleted" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=", "value": "alation_analytics" }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "xact_commit" ], "type": "field" },
       { "params": [ "Committed Transaction " ], "type": "alias" }
      ],
      [
       { "params": [ "xact_rollback" ], "type": "field" },
       { "params": [ "Rolled back Transaction" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=", "value": "alation_analytics" }
     ]
    }
   ]
  },
  {
   "title": "Total time the statement spent reading/writing blocks (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "blk_read_time" ], "type": "field" }
      ],
      [
       { "params": [ "blk_write_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=", "value": "alation_analytics" }
     ]
    }
   ]
  },
  { "title": "Docker Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Container CPU usage percentage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Container Memory usage (Mb)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "RabbitMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Message Delivered",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_queue",
     "groupBy": [
      { "params": [ "queue" ], "type": "tag" }
     ],
     "measurement": "rabbitmq_overview",
     "select": [
      [
       { "params": [ "messages_delivered" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queue Size (Byte)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_queue",
     "groupBy": [
      { "params": [ "queue" ], "type": "tag" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "message_bytes" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}